# Site settings
title: mingze gao blog
email: mingze.gao.gmz@gmail.com
description: some thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MingzeGao2.github.io" # the base hostname & protocol for your site
twitter_username: MingzeGao
github_username:  MingzeGao2

# Build settings
markdown: kramdown
